language: python
python:
- '2.7'
install: pip install -r requirements.txt --use-mirrors
script: python setup.py test
deploy:
  provider: pypi
  user: azavea
  password:
    secure: UcbzWsKE4su3F/3/HXvfaFlhQdqhma83msImD7vGK2ZYY9BSsMsIIqd3ouIq4Aeb9FtUkfC0agY+XV1pw1vSZAZFQbEa3w+axa/IHcEEeFAC3YxNSnqC7fvZRgVKXn/jO2bcraNK5yKOUZv/stjXj+bYEvHuwL5ZXjkTnwsal6gX9riAt6wGZSyhSA4QkyIq9l7ju84yy4suhvlo4+aa0WBqf5hE/ZX6QXEpI+ig4UYIsr/eJeDa0S5bs9X+hwIGgQG/2gumtdWdaHlT555/WPux76oi5h5vQEaEFqjirg0oSIXVSnxVih0LZFyI9LmH45vfUvGVrujE+UKLb0XmYeoaaOIjEQUc0LHxYMKUgrzyg/IMKCDY1tiNLlTsctHN3YIBSGVDjzPePtMHO9Gdm/CmS5tmja1YpdFg7YwAoYd6Hj7pQrjnsH2ueHcuWixYAEg3xyV5ASAqPv53b4rv5kl1tA3xZxlP1e9vZkZIT8olsjtOp5AFD7VCqrEHYc2e1+8aWXYHGcTf5oTzkBPYH89SQIC1MSRYdw3JddWlju8V1gr510x1B6kbgs4GFpKRy94ggf/0Scw/HCAzCery4WxfEdWC9owt40Lx5Az/tKrMAHkHAK6o2nX11XQc/ESDT02XSSgMY2ulAN6qHs5B5f85cl9hdV23QArQVa7D7ZQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: WikiWatershed/rapid-watershed-delineation
