version: '2'
services:
  app:
    restart: always
    image: docker-rwd
    build: .
    ports:
      - "5000:5000"
    volumes:
        - $RWD_DATA:/opt/rwd-data
        - ./src/api:/usr/src/api
        - ./rwd_nhd:/usr/src/rwd_nhd
        - ./rwd_drb:/usr/src/rwd_drb
    entrypoint: /usr/local/bin/gunicorn -w 4 --log-syslog --bind 0.0.0.0:5000 --reload main:app
